### ISSUE TITLE
There should be a way to sort resources

### ISSUE THREAD

**Issue by Soulou** [Scalingo/developers.scalingo.com#2]
'Applications' are more important than other resources usually, it would be great to make it appear first.

**Comment by yannski** [comment]
I don't agree with that. It would be better though that the list of resources is listed alphabetically. See https://github.com/Scalingo/developers.scalingo.com/commit/0112facd4ed3fd1bb3bed9f186d9d6bbfd782f33

**Comment by Soulou** [comment]
Ok for me
